database:
  host: localhost
  port: 3306
  username: root
  password: WUliang1998102
  database: kubeInsight
  charset: utf8
  parseTime: true
  loc: Local

redis:
  user: ""
  password: ""
  host: localhost
  port: 6379
  db: 0

